module.exports = {
  'name.txt': {
    path: 'name.txt.enc',
    mime: 'text/plain',
    key: 'vScyqmJKqGl73mJkuwm/zPBQk0wct9eQ5wPE8laGcWM=',
    iv: '6lNU+2vxJw6SFgse',
    authTag: 'DYDQeVMrIvgT98E3pzpjkw==',
  },
  'NYT.txt': {
    path: 'NYT.txt.enc',
    mime: 'text/plain',
    key: 'vScyqmJKqGl73mJkuwm/zPBQk0wct9eQ5wPE8laGcWM=',
    iv: '6lNU+2vxJw6SFgse',
    authTag: 'gadZhS1QozjEmfmHLblzbg==',
  },
  'tortoise.jpg': {
    path: 'tortoise.jpg.enc',
    mime: 'image/jpeg',
    key: 'vScyqmJKqGl73mJkuwm/zPBQk0wct9eQ5wPE8laGcWM=',
    iv: '6lNU+2vxJw6SFgse',
    authTag: 'ELry8dZ3djg8BRB+7TyXZA==',
  },
  'water.png': {
    path: 'water.png.enc',
    mime: 'image/png',
    key: 'vScyqmJKqGl73mJkuwm/zPBQk0wct9eQ5wPE8laGcWM=',
    iv: '6lNU+2vxJw6SFgse',
    authTag: 'O7OO9ITvYg5EgdNdIVwbVw==',
  },
  'turtl.gif': {
    path: 'turtl.gif.enc',
    mime: 'image/gif',
    key: 'vScyqmJKqGl73mJkuwm/zPBQk0wct9eQ5wPE8laGcWM=',
    iv: '6lNU+2vxJw6SFgse',
    authTag: '6Q+67PfEE/4/qp9CPgR4Hg==',
  },
  'africa.topo.json': {
    path: 'africa.topo.json.enc',
    mime: 'application/json',
    key: 'vScyqmJKqGl73mJkuwm/zPBQk0wct9eQ5wPE8laGcWM=',
    iv: '6lNU+2vxJw6SFgse',
    authTag: 'jw6UL2SQjOr0IwgF6TzxFA==',
  },
  'k.webm': {
    path: 'k.webm.enc',
    mime: 'video/webm',
    key: 'vScyqmJKqGl73mJkuwm/zPBQk0wct9eQ5wPE8laGcWM=',
    iv: '6lNU+2vxJw6SFgse',
    authTag: 'K3MVZrK2/6+n8/p/74mXkQ==',
  },
  'river.jpg': {
    path: 'river.jpg.enc',
    mime: 'image/jpeg',
    key: 'vScyqmJKqGl73mJkuwm/zPBQk0wct9eQ5wPE8laGcWM=',
    iv: '6lNU+2vxJw6SFgse',
    authTag: 'xdbXMuw8Q+uSnOYEXtMr4A==',
  },
  'patreon.mp4': {
    path: 'patreon.mp4.enc',
    mime: 'video/mp4',
    key: 'vScyqmJKqGl73mJkuwm/zPBQk0wct9eQ5wPE8laGcWM=',
    iv: '6lNU+2vxJw6SFgse',
    authTag: 'Mqgmwj9IvLEeBjhwrkYpBg==',
  },
  'Earth.jpg': {
    path: 'Earth.jpg.enc',
    mime: 'image/jpeg',
    key: 'vScyqmJKqGl73mJkuwm/zPBQk0wct9eQ5wPE8laGcWM=',
    iv: '6lNU+2vxJw6SFgse',
    authTag: 'v86dSoD5yu4iaDZdPYWTDA==',
  },
};
