name: ci
on: push

jobs:
  build-and-upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/commands/dependencies/install_deps
      - name: Build
        run: pnpm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist/
            ts-build/

  run-karma:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/commands/dependencies/install_deps
      - run: pnpm run test:browserstack

  run-depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/commands/dependencies/install_deps
      - run: pnpm run depcheck

  run-pre-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100 # need the history to do a changed files check below (source, origin)
      - uses: actions/setup-python@v4
      - uses: ./.github/commands/dependencies/install_deps
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --source ${{ github.event.pull_request.base.sha || 'HEAD~1' }} --origin ${{ github.event.pull_request.head.sha || 'HEAD' }}

  build-to-npm:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - run-karma
      - run-depcheck
      - build-and-upload-artifacts
      - run-pre-commits
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/commands/dependencies/install_deps
      - name: Configure npm authentication
        run: |
          pnpm config set always-auth true
          pnpm config set //registry.npmjs.org/:_authToken "${{ secrets.NPM_TOKEN }}"
      - name: Publish to npm
        run: pnpm publish

  build-to-github-packages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - run-karma
      - run-depcheck
      - build-and-upload-artifacts
      - run-pre-commits
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/commands/dependencies/install_deps
      - name: Configure GitHub Packages authentication
        run: |
          pnpm config set always-auth true
          pnpm config set registry https://npm.pkg.github.com
          pnpm config set //npm.pkg.github.com/:_authToken "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish to GitHub Packages
        run: pnpm publish
